// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VocabuAI.Domain.Learning;
using VocabuAI.Infrastructure.Database;

#nullable disable

namespace VocabuAI.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228173000_AddFlashCardLearningState")]
    partial class AddFlashCardLearningState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            var jsonOptions = new JsonSerializerOptions(JsonSerializerDefaults.Web);
            var taskTypeCountsConverter = new ValueConverter<Dictionary<LearningTaskType, int>, string>(
                value => JsonSerializer.Serialize(value, jsonOptions),
                value => JsonSerializer.Deserialize<Dictionary<LearningTaskType, int>>(value, jsonOptions) ?? new Dictionary<LearningTaskType, int>());
            var taskTypeCountsComparer = new ValueComparer<Dictionary<LearningTaskType, int>>(
                (left, right) =>
                    ReferenceEquals(left, right)
                    || (left != null
                        && right != null
                        && left.Count == right.Count
                        && left.All(item => right.ContainsKey(item.Key) && right[item.Key] == item.Value)),
                value => value == null ? 0 : value.Aggregate(0, (hash, item) => HashCode.Combine(hash, item.Key, item.Value)),
                value => value == null ? new Dictionary<LearningTaskType, int>() : value.ToDictionary(item => item.Key, item => item.Value));

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForeignLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Synonyms")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FlashCards", (string)null);
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardLearningStateDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Box")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCountTotal")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectStreak")
                        .HasColumnType("integer");

                    b.Property<Dictionary<LearningTaskType, int>>("CorrectCountsByQuestionTypeInCurrentBox")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasConversion(taskTypeCountsConverter);

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlashCardId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProgressPointsInCurrentBox")
                        .HasColumnType("integer");

                    b.Property<int>("WrongCountTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlashCardId")
                        .IsUnique();

                    b.ToTable("FlashCardLearningState", (string)null);

                    b.HasCheckConstraint("CK_FlashCardLearningState_Box_Range", "\"Box\" >= 1 AND \"Box\" <= 5");

                    b.Property<Dictionary<LearningTaskType, int>>("CorrectCountsByQuestionTypeInCurrentBox")
                        .Metadata.SetValueComparer(taskTypeCountsComparer);
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.UserDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardDb", b =>
                {
                    b.HasOne("VocabuAI.Infrastructure.Database.Entities.UserDb", "User")
                        .WithMany("FlashCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardLearningStateDb", b =>
                {
                    b.HasOne("VocabuAI.Infrastructure.Database.Entities.FlashCardDb", "FlashCard")
                        .WithOne("LearningState")
                        .HasForeignKey("VocabuAI.Infrastructure.Database.Entities.FlashCardLearningStateDb", "FlashCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashCard");
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardDb", b =>
                {
                    b.Navigation("LearningState");
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.UserDb", b =>
                {
                    b.Navigation("FlashCards");
                });
#pragma warning restore 612, 618
        }
    }
}
