// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VocabuAI.Infrastructure.Database;

#nullable disable

namespace VocabuAI.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307183532_AddGeneratedLearningTextHistory")]
    partial class AddGeneratedLearningTextHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForeignLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForeignLanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalLanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Synonyms")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FlashCards", (string)null);
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardLearningStateDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Box")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCountTotal")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectCountsByQuestionTypeInCurrentBox")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CorrectStreak")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlashCardId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProgressPointsInCurrentBox")
                        .HasColumnType("integer");

                    b.Property<int>("WrongCountTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlashCardId")
                        .IsUnique();

                    b.ToTable("FlashCardLearningState", null, t =>
                        {
                            t.HasCheckConstraint("CK_FlashCardLearningState_Box_Range", "\"Box\" >= 1 AND \"Box\" <= 5");
                        });
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.GeneratedLearningTextDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedLearningTexts", (string)null);
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.UserDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTimeUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultForeignFlashCardLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("en");

                    b.Property<string>("DefaultLocalFlashCardLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("de");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSelectedAiProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ollama");

                    b.Property<string>("OpenAiApiKeyEncrypted")
                        .HasColumnType("text");

                    b.Property<int>("OpenAiMonthlyTokenLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("OpenAiTokensUsedMonthKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<int>("OpenAiTokensUsedThisMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardDb", b =>
                {
                    b.HasOne("VocabuAI.Infrastructure.Database.Entities.UserDb", "User")
                        .WithMany("FlashCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardLearningStateDb", b =>
                {
                    b.HasOne("VocabuAI.Infrastructure.Database.Entities.FlashCardDb", "FlashCard")
                        .WithOne("LearningState")
                        .HasForeignKey("VocabuAI.Infrastructure.Database.Entities.FlashCardLearningStateDb", "FlashCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashCard");
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.GeneratedLearningTextDb", b =>
                {
                    b.HasOne("VocabuAI.Infrastructure.Database.Entities.UserDb", "User")
                        .WithMany("GeneratedLearningTexts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.FlashCardDb", b =>
                {
                    b.Navigation("LearningState");
                });

            modelBuilder.Entity("VocabuAI.Infrastructure.Database.Entities.UserDb", b =>
                {
                    b.Navigation("FlashCards");

                    b.Navigation("GeneratedLearningTexts");
                });
#pragma warning restore 612, 618
        }
    }
}
